# Generated by Django 5.2 on 2025-05-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
