# Generated by Django 5.2 on 2025-05-01 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_description_alter_brand_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField(default=False)),
                ('negative', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('reactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='vote_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vote'),
        ),
    ]
