# Generated by Django 5.2 on 2025-05-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vote_alter_review_vote_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='vote_score',
            new_name='vote',
        ),
    ]
