# Generated by Django 5.1.4 on 2025-02-01 14:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='Profile/', validators=[main.models.validate_size]),
        ),
    ]
