# Generated by Django 5.1.4 on 2025-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_profilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Profile'),
        ),
    ]
