# Generated by Django 5.1.4 on 2025-01-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_profilemodel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
